[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "netlify-plugin-a11y"
  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]  
    # required config
    checkPaths = [
      '/',
      '/aktivitaet-posts',
      '/aktivitaeten',
      '/impressum',
      '/netzwerk',
      '/projekt-items',
      '/projekte',
      '/projekte/Grossmünster-Modell-Projekt',
      '/projekte/kochrezepte',
      '/projekte/kochrezepte-projekt',
      '/projekte/talente',
      '/projekte/talente-projekt',
      '/spenden',
      '/ueberuns',
      '/vorstand',
      '/vorstand-members'
    ] # you can give an array of directories or paths to html files, that you want to run a11y checks on
    debugMode = true # extra logging for plugin developers
