backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: "aktivitaetpost"
    label: "Aktivitäten"
    folder: "src/pages/aktivitaet-posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:        
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aktivitaet-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Suchmaschine Beschreibung", name: "seodescription", widget: "string"}
      - {label: "Veranstaltungsdatum", name: "date", widget: "datetime",  timeFormat: false, dateFormat: "DD.MM.YYYY"}
      - {label: "Anmeldeformular anzeigen", name: "anmeldeformularanzeigen", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "vorstandmember"
    label: "Vorstand"
    folder: "src/pages/vorstand-members"
    create: true
    fields:        
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "vorstand"}
      - {label: "Portrait", name: "portrait", widget: object, fields: [{label: PortraitImage, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Funktion", name: "funktion", widget: "string"}
      - {label: "Reihenfolge", name: "reihenfolge", widget: "number"}

  - name: "projekte"
    label: "Projekte"
    folder: "src/pages/projekt-items"
    create: true
    fields:        
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projekt-item"}
      - {label: "Bild", name: "bild", widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Beschreibung", name: "beschreibung", widget: "string"}
      - {label: "Reihenfolge", name: "reihenfolge", widget: "number"}

  - name: "portraits"
    label: "Portraits"
    folder: "src/pages/projekte/portraits"
    create: true
    fields:        
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portrait-item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Suchmaschine Beschreibung", name: "seodescription", widget: "string"} 
      - {label: "Fotogallerie", name: "photogallery", widget: "list", field: {label: "Bild", name: "bild", widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "kochrezepte"
    label: "Kochrezepte"
    folder: "src/pages/projekte/kochrezepte"
    create: true
    fields:        
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kochrezept-item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Kategorie", name: "kategorie", widget: "select", options: ["1. Suppen und Salate", "2. Hauptspeisen", "3. Dessert"], default: ["2. Hauptspeisen"]}
      - {label: "Suchmaschine Beschreibung", name: "seodescription", widget: "string"}
      - {label: "body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Startseite"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/aktivitaeten/index.md"
        label: "Aktivitäten"
        name: "aktivitaeten"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "aktivitaeten-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/vorstand/index.md"
        label: "Vorstand"
        name: "vorstand"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "vorstand-page"}
          - {label: Title, name: title, widget: string}
      - file: "src/pages/projekte/index.md"
        label: "Projekte"
        name: "projekte"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projekte-page"}
          - {label: Title, name: title, widget: string}
      - file: "src/pages/projekte/kochrezepte-projekt/index.md"
        label: "Kochrezepte"
        name: "kochrezepte-projekt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kochrezepte-projekt-page"}
          - {label: Title, name: title, widget: string}
      - file: "src/pages/projekte/portraits-projekt/index.md"
        label: "Portraits"
        name: "portraits-projekt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portraits-projekt-page"}
          - {label: Title, name: title, widget: string}
      - file: "src/pages/projekte/grossmuenster-modell-reparatur-projekt/index.md"
        label: "Grossmünster Reparatur Projekt"
        name: "grossmuenster-modell-reparatur-projekt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "grossmuenster-modell-projekt-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/impressum/index.md"
        label: "Impressum"
        name: "impressum"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "impressum-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/spenden/index.md"
        label: "Spenden"
        name: "spenden"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "spenden-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/ueberuns/index.md"
        label: "Über uns"
        name: "ueberuns"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ueberuns-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}